/**
 * Draft Open Policy Agent (Rego) previews.
 *
 * For each finding we generate a short, readable Rego policy that shows *how*
 * SecuriX would bring that exact pathway under control. These are previews, not
 * enforcement — the free tool shows the policy; SecuriX runs it, in Draft-Only
 * mode first so nothing breaks. Every block is labelled to make that clear.
 *
 * The goal is the "aha then bridge": the CISO sees the risk, then sees that a
 * dozen lines of policy at a gateway would close it — which is the SecuriX
 * product.
 */

import type { Finding } from './types.js';

const HEADER = '# DRAFT — preview generated by SecuriX. Enforced in Draft-Only mode first.';

function mcpPolicy(f: Finding): string {
  const domains = f.dataDomains.filter((d) => d !== 'unknown' && d !== 'network');
  const list = (domains.length ? domains : ['sensitive']).map((d) => `"${d}"`).join(', ');
  return `${HEADER}
package securix.mcp.gateway

import rego.v1

# Broker every MCP tool call through the SecuriX MCP Gateway.
sensitive_domains := {${list}}

default allow := false

allow if {
    input.caller.identity != ""            # authenticated agent, not anonymous
    not touches_sensitive_without_approval
}

touches_sensitive_without_approval if {
    some d in input.tool.data_domains
    sensitive_domains[d]
    not input.request.approved_by_policy   # requires an explicit allow rule
}

# Redact matched data before it is returned to the model provider.
redact contains field if {
    some field in input.response.fields
    field.classification in sensitive_domains
}`;
}

function llmPolicy(f: Finding): string {
  const provider = f.title.match(/Direct (.+?) API access/)?.[1] ?? 'the AI provider';
  return `${HEADER}
package securix.llm.gateway

import rego.v1

# Force all traffic to ${provider} through the SecuriX LLM Gateway,
# so keys are held centrally and every prompt is inspected.
default allow := false

allow if {
    input.egress.via_gateway == true       # no direct-to-provider calls
    not prompt_leaks_regulated_data
}

prompt_leaks_regulated_data if {
    some match in input.dlp.matches         # PII / secrets / source detected
    match.action == "block"
}

# What the gateway records for the audit trail SecuriX gives you.
audit := {
    "user": input.identity.user,
    "provider": input.egress.provider,
    "dlp_matches": count(input.dlp.matches),
}`;
}

function guardrailPolicy(): string {
  return `${HEADER}
package securix.agent.guardrail

import rego.v1

# Baseline guardrail for autonomous agents behind SecuriX.
default allow := false

allow if {
    input.agent.registered == true          # known, inventoried agent
    input.action.tool in data.securix.approved_tools
    not input.action.targets_production      # no unattended prod access
}`;
}

export function regoFor(f: Finding): string {
  switch (f.control) {
    case 'llm-gateway':
      return f.kind === 'provider-key' ? llmPolicy(f) : guardrailPolicy();
    case 'mcp-gateway':
      return mcpPolicy(f);
    case 'both':
      return f.kind === 'agent-framework' ? guardrailPolicy() : mcpPolicy(f);
    default:
      return guardrailPolicy();
  }
}

/** Attach a draft Rego preview to every finding, in place. */
export function attachRego(findings: Finding[]): Finding[] {
  return findings.map((f) => ({ ...f, rego: regoFor(f) }));
}
